services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@database:5432/medical_records?serverVersion=16&charset=utf8"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: medical_records
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony"]
      timeout: 5s
      retries: 10
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
